In [58]:
import pandas as pd
import glob
import os

# Trova tutti i CSV nella cartella regions
file_list = glob.glob("./regions/*.csv")

df_list = []

for file in file_list:
    # Estrai il nome della regione dal nome del file
    nome_file = os.path.basename(file)  # es: subito_cars_abruzzo.csv
    regione = nome_file.replace("subito_cars_", "").replace(".csv", "")

    # Leggi il CSV
    df = pd.read_csv(file)

    # Aggiungi la colonna 'region'
    df["region"] = regione

    # Aggiungi alla lista
    df_list.append(df)

# Unisci tutti i DataFrame
df = pd.concat(df_list, ignore_index=True)

# Mostra le prime righe
print(df.head())
print("the shape of the dataframe is: ", df_totale.shape)

                                                 url  \
0  https://www.subito.it/auto/fiat-600-1-2-hybrid...
1  https://www.subito.it/auto/alfa-romeo-stelvio-...
2  https://www.subito.it/auto/volkswagen-polo-1-4...
3  https://www.subito.it/auto/opel-zafira-1-7-cdt...
4  https://www.subito.it/auto/maserati-quattropor...

                                         brand_model     price     year  \
0               FIAT 600 1.2 HYBRID 74KW (100CV) DCT  21.970 €     2025
1     Alfa Romeo Stelvio 2.2 cc 210 CV Q4 Veloce KM0  28.560 €  12/2024
2  VOLKSWAGEN Polo 1.4 TDI highline - 2017 come n...  10.490 €  12/2016
3             Opel Zafira 1.7 CDTI 110CV ecoFLEX One   5.000 €  06/2013
4      Maserati Quattroporte V6 430 CV AWD Modena Q4  74.900 €  03/2023

     mileage fuel_type transmission emission_standard        body_type  \
0        NaN    Ibrida   Automatico     - (Emissioni)  SUV/Fuoristrada
1        NaN    Diesel   Automatico            Euro 6  SUV/Fuoristrada
2  185000 Km    Diesel      Manuale            Euro 6    - (Tipologia)
3  161000 Km    Diesel      Manuale            Euro 5       Monovolume
4   79700 Km   Benzina   Automatico            Euro 6          Berlina

                                         description    region
0  Veicolo nuovo non immatricolato. \n\nDEK:[8681...  piemonte
1  Autovincenti è un Autosalone Multibrand specia...  piemonte
2  Vendo Volkswagen Polo 1.4 TDI Highline bluemot...  piemonte
3  Auto tenuta in ottime condizioni\n\nMeccanica ...  piemonte
4  TOPCARSWEB Luxury vi da il benvenuto.\n\nOltre...  piemonte
the shape of the dataframe is:  (154334, 11)

THE NEXT STEP IS TO UNDERSTAND HOW MANY UNIQUE ARTICLES WE HAVE

In [59]:
# Save all the links in a set and count unique links
unique_links = set(df["url"])
print("the number of unique links is: ", len(unique_links))
# the number of unique links is:  154334

the number of unique links is:  154334

CONVERSION OF THE VARIABLES INTO NUMBERS
START FROM FUEL_TYPE

In [60]:
unique_fuel_types = set(df["fuel_type"])
print("the number of unique fuel types is: ", len(unique_fuel_types))
print("the unique fuel types are: ", unique_fuel_types)
# the unique fuel types are:  {'- (Carburante)', 'Elettrica', 'Benzina', 'Ibrida', 'Gpl', 'Altro', 'Metano', 'Diesel', nan}
# need to remove '- (Carburante)' , 'Altro', and nan
df = df[~df["fuel_type"].isin(["- (Carburante)", "Altro", None])].dropna()
unique_fuel_types = set(df["fuel_type"])
print("the number of unique fuel types is: ", len(unique_fuel_types))
print("the unique fuel types are: ", unique_fuel_types)

# NEED TO CONVERT FROM {'Elettrica','Diesel', 'Benzina', 'Ibrida', 'Gpl', 'Metano'} TO NUMERIC VALUES
fuel_type_mapping = {
    "Elettrica": 0,
    "Diesel": 1,
    "Benzina": 2,
    "Ibrida": 3,
    "Gpl": 4,
    "Metano": 5
}
# Map the fuel types to numeric values
df["fuel_type"] = df["fuel_type"].map(fuel_type_mapping)
df

the number of unique fuel types is:  9
the unique fuel types are:  {'- (Carburante)', 'Elettrica', 'Benzina', 'Ibrida', 'Gpl', 'Altro', 'Metano', 'Diesel', nan}
the number of unique fuel types is:  6
the unique fuel types are:  {'Elettrica', 'Benzina', 'Ibrida', 'Gpl', 'Metano', 'Diesel'}

,url,brand_model,price,year,mileage,fuel_type,transmission,emission_standard,body_type,description,region
2,https://www.subito.it/auto/volkswagen-polo-1-4...,VOLKSWAGEN Polo 1.4 TDI highline - 2017 come n...,10.490 €,12/2016,185000 Km,1,Manuale,Euro 6,- (Tipologia),Vendo Volkswagen Polo 1.4 TDI Highline bluemot...,piemonte
3,https://www.subito.it/auto/opel-zafira-1-7-cdt...,Opel Zafira 1.7 CDTI 110CV ecoFLEX One,5.000 €,06/2013,161000 Km,1,Manuale,Euro 5,Monovolume,Auto tenuta in ottime condizioni\n\nMeccanica ...,piemonte
4,https://www.subito.it/auto/maserati-quattropor...,Maserati Quattroporte V6 430 CV AWD Modena Q4,74.900 €,03/2023,79700 Km,2,Automatico,Euro 6,Berlina,TOPCARSWEB Luxury vi da il benvenuto.\n\nOltre...,piemonte
5,https://www.subito.it/auto/mazda-mx-5-roadster...,Mazda MX-5 Roadster Coupé 1.8L Fire,15.990 €,03/2012,64254 Km,2,Manuale,Euro 5,Cabrio,DEK:[9553009]\nAUTO CON MANUTENZIONE COMPLETA ...,piemonte
7,https://www.subito.it/auto/fiat-idea-torino-60...,Fiat Idea,2.950 €,04/2011,257000 Km,1,Manuale,- (Emissioni),Berlina,VENGA A TROVARCI: LA VETTURA E' DISPONIBILE DA...,piemonte
...,...,...,...,...,...,...,...,...,...,...,...
154329,https://www.subito.it/auto/seat-arona-1-0-ecot...,Seat Arona 1.0 EcoTSI XPERIENCE,16.700 €,12/2021,33000 Km,2,Manuale,Euro 6,SUV/Fuoristrada,"SEAT VIRTUAL COCKPIT DA 10,25 pollici\nFari Fu...",calabria
154330,https://www.subito.it/auto/peugeut-2008-cosenz...,Peugeut 2008,15.999 €,01/2019,20000 Km,1,Automatico,Euro 6,Monovolume,"Vendo causa inutizzo splendida peugeut 2008, c...",calabria
154331,https://www.subito.it/auto/bmw-x4-xdrive20d-xl...,BMW X4 xDrive20d xLine,25.900 €,02/2018,110543 Km,1,Automatico,Euro 6,SUV/Fuoristrada,DEK:[9487127]\nGRUPPO FORMULA 3 // Messina - R...,calabria
154332,https://www.subito.it/auto/audi-a-5-sportback-...,Audi a 5 sportback quattro tfsi,23.700 €,06/2013,72000 Km,2,Automatico,Euro 5,Station Wagon,Vendo bellissima audi a 5 tfsi con 72 mila km ...,calabria
154333,https://www.subito.it/auto/fiat-doblo-doblo-1-...,Fiat Doblo Doblò 1.6 MJT 90CV S&S PC-TN Cargo ...,11.990 €,04/2021,143011 Km,1,Manuale,Euro 6,Monovolume,Fiat Doblo' 1.6 MJT 90CV CARGO BUSINESS 3 POST...,calabria

NOW WE NEED TO REMOVE THE EURO SYMBOL FROM THE PRICE AND REMOVE THE DOTS

In [61]:
# need to remove the rows without a price
# 1. keep only rows where 'price' is not NaN
df = df[df["price"].notna()]

# 2. Remove the euro sign and any commas or dots
df["price"] = df["price"].replace({'€': '', r'[.,]': ''}, regex=True)

# 3. remove whute spaces
df["price"] = df["price"].str.strip()

# 4. remove empty strings
df = df[df["price"] != ""]

# 5. convert to integer
df["price"] = df["price"].astype(int) 
df

,url,brand_model,price,year,mileage,fuel_type,transmission,emission_standard,body_type,description,region
2,https://www.subito.it/auto/volkswagen-polo-1-4...,VOLKSWAGEN Polo 1.4 TDI highline - 2017 come n...,10490,12/2016,185000 Km,1,Manuale,Euro 6,- (Tipologia),Vendo Volkswagen Polo 1.4 TDI Highline bluemot...,piemonte
3,https://www.subito.it/auto/opel-zafira-1-7-cdt...,Opel Zafira 1.7 CDTI 110CV ecoFLEX One,5000,06/2013,161000 Km,1,Manuale,Euro 5,Monovolume,Auto tenuta in ottime condizioni\n\nMeccanica ...,piemonte
4,https://www.subito.it/auto/maserati-quattropor...,Maserati Quattroporte V6 430 CV AWD Modena Q4,74900,03/2023,79700 Km,2,Automatico,Euro 6,Berlina,TOPCARSWEB Luxury vi da il benvenuto.\n\nOltre...,piemonte
5,https://www.subito.it/auto/mazda-mx-5-roadster...,Mazda MX-5 Roadster Coupé 1.8L Fire,15990,03/2012,64254 Km,2,Manuale,Euro 5,Cabrio,DEK:[9553009]\nAUTO CON MANUTENZIONE COMPLETA ...,piemonte
7,https://www.subito.it/auto/fiat-idea-torino-60...,Fiat Idea,2950,04/2011,257000 Km,1,Manuale,- (Emissioni),Berlina,VENGA A TROVARCI: LA VETTURA E' DISPONIBILE DA...,piemonte
...,...,...,...,...,...,...,...,...,...,...,...
154329,https://www.subito.it/auto/seat-arona-1-0-ecot...,Seat Arona 1.0 EcoTSI XPERIENCE,16700,12/2021,33000 Km,2,Manuale,Euro 6,SUV/Fuoristrada,"SEAT VIRTUAL COCKPIT DA 10,25 pollici\nFari Fu...",calabria
154330,https://www.subito.it/auto/peugeut-2008-cosenz...,Peugeut 2008,15999,01/2019,20000 Km,1,Automatico,Euro 6,Monovolume,"Vendo causa inutizzo splendida peugeut 2008, c...",calabria
154331,https://www.subito.it/auto/bmw-x4-xdrive20d-xl...,BMW X4 xDrive20d xLine,25900,02/2018,110543 Km,1,Automatico,Euro 6,SUV/Fuoristrada,DEK:[9487127]\nGRUPPO FORMULA 3 // Messina - R...,calabria
154332,https://www.subito.it/auto/audi-a-5-sportback-...,Audi a 5 sportback quattro tfsi,23700,06/2013,72000 Km,2,Automatico,Euro 5,Station Wagon,Vendo bellissima audi a 5 tfsi con 72 mila km ...,calabria
154333,https://www.subito.it/auto/fiat-doblo-doblo-1-...,Fiat Doblo Doblò 1.6 MJT 90CV S&S PC-TN Cargo ...,11990,04/2021,143011 Km,1,Manuale,Euro 6,Monovolume,Fiat Doblo' 1.6 MJT 90CV CARGO BUSINESS 3 POST...,calabria

COONVER THE YEAR INTO A SINGLE INTEGER

In [62]:
def convert_year(value):
    # Convert to string and strip spaces
    value = str(value).strip()

    # If it contains any letters, discard it
    if any(char.isalpha() for char in value):
        return None

    # If it's a format like "MM/YYYY"
    if "/" in value:
        parts = value.split("/")
        if len(parts) == 2 and parts[0].isdigit() and parts[1].isdigit():
            month, year = parts
            month = month.zfill(2)
            return int(year + month)
        else:
            return None

    # If it's a pure year like "2025"
    if value.isdigit():
        return int(value + "01")

    return None

# Apply the conversion
df["year"] = df["year"].apply(convert_year)

# Drop rows where the conversion failed (None or NaN)
df = df.dropna(subset=["year"])
df

,url,brand_model,price,year,mileage,fuel_type,transmission,emission_standard,body_type,description,region
2,https://www.subito.it/auto/volkswagen-polo-1-4...,VOLKSWAGEN Polo 1.4 TDI highline - 2017 come n...,10490,201612.0,185000 Km,1,Manuale,Euro 6,- (Tipologia),Vendo Volkswagen Polo 1.4 TDI Highline bluemot...,piemonte
3,https://www.subito.it/auto/opel-zafira-1-7-cdt...,Opel Zafira 1.7 CDTI 110CV ecoFLEX One,5000,201306.0,161000 Km,1,Manuale,Euro 5,Monovolume,Auto tenuta in ottime condizioni\n\nMeccanica ...,piemonte
4,https://www.subito.it/auto/maserati-quattropor...,Maserati Quattroporte V6 430 CV AWD Modena Q4,74900,202303.0,79700 Km,2,Automatico,Euro 6,Berlina,TOPCARSWEB Luxury vi da il benvenuto.\n\nOltre...,piemonte
5,https://www.subito.it/auto/mazda-mx-5-roadster...,Mazda MX-5 Roadster Coupé 1.8L Fire,15990,201203.0,64254 Km,2,Manuale,Euro 5,Cabrio,DEK:[9553009]\nAUTO CON MANUTENZIONE COMPLETA ...,piemonte
7,https://www.subito.it/auto/fiat-idea-torino-60...,Fiat Idea,2950,201104.0,257000 Km,1,Manuale,- (Emissioni),Berlina,VENGA A TROVARCI: LA VETTURA E' DISPONIBILE DA...,piemonte
...,...,...,...,...,...,...,...,...,...,...,...
154329,https://www.subito.it/auto/seat-arona-1-0-ecot...,Seat Arona 1.0 EcoTSI XPERIENCE,16700,202112.0,33000 Km,2,Manuale,Euro 6,SUV/Fuoristrada,"SEAT VIRTUAL COCKPIT DA 10,25 pollici\nFari Fu...",calabria
154330,https://www.subito.it/auto/peugeut-2008-cosenz...,Peugeut 2008,15999,201901.0,20000 Km,1,Automatico,Euro 6,Monovolume,"Vendo causa inutizzo splendida peugeut 2008, c...",calabria
154331,https://www.subito.it/auto/bmw-x4-xdrive20d-xl...,BMW X4 xDrive20d xLine,25900,201802.0,110543 Km,1,Automatico,Euro 6,SUV/Fuoristrada,DEK:[9487127]\nGRUPPO FORMULA 3 // Messina - R...,calabria
154332,https://www.subito.it/auto/audi-a-5-sportback-...,Audi a 5 sportback quattro tfsi,23700,201306.0,72000 Km,2,Automatico,Euro 5,Station Wagon,Vendo bellissima audi a 5 tfsi con 72 mila km ...,calabria
154333,https://www.subito.it/auto/fiat-doblo-doblo-1-...,Fiat Doblo Doblò 1.6 MJT 90CV S&S PC-TN Cargo ...,11990,202104.0,143011 Km,1,Manuale,Euro 6,Monovolume,Fiat Doblo' 1.6 MJT 90CV CARGO BUSINESS 3 POST...,calabria

In [ ]:
# conversion of the mileage column. just remove the ' km' and convert to integer
df["mileage"] = df["mileage"].replace({' Km': '', r'[.,]': '',' km': ''}, regex=True)
df# Optional: make sure df is a real copy to avoid warningsaaaopy to avoid warningsaaaopy to avoid warningsaaaopy to avoid warningsaaa
df = df.copy()

# Clean the 'mileage' column
df["mileage"] = df["mileage"].replace({' Km': '', ' km': '', r'[.,]': ''}, regex=True)

# Strip any whitespace
df["mileage"] = df["mileage"].str.strip()

# Drop empty strings or NaNs
df = df[df["mileage"].notna() & (df["mileage"] != "")]

# Convert to integer
df["mileage"] = df["mileage"].astype(int)

/var/folders/61/p_sfvpq16gj0n_crsg1gv2980000gn/T/ipykernel_30808/2428586121.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["mileage"] = df["mileage"].replace({' Km': '', r'[.,]': '',' km': ''}, regex=True)

,url,brand_model,price,year,mileage,fuel_type,transmission,emission_standard,body_type,description,region
2,https://www.subito.it/auto/volkswagen-polo-1-4...,VOLKSWAGEN Polo 1.4 TDI highline - 2017 come n...,10490,201612.0,185000,1,Manuale,Euro 6,- (Tipologia),Vendo Volkswagen Polo 1.4 TDI Highline bluemot...,piemonte
3,https://www.subito.it/auto/opel-zafira-1-7-cdt...,Opel Zafira 1.7 CDTI 110CV ecoFLEX One,5000,201306.0,161000,1,Manuale,Euro 5,Monovolume,Auto tenuta in ottime condizioni\n\nMeccanica ...,piemonte
4,https://www.subito.it/auto/maserati-quattropor...,Maserati Quattroporte V6 430 CV AWD Modena Q4,74900,202303.0,79700,2,Automatico,Euro 6,Berlina,TOPCARSWEB Luxury vi da il benvenuto.\n\nOltre...,piemonte
5,https://www.subito.it/auto/mazda-mx-5-roadster...,Mazda MX-5 Roadster Coupé 1.8L Fire,15990,201203.0,64254,2,Manuale,Euro 5,Cabrio,DEK:[9553009]\nAUTO CON MANUTENZIONE COMPLETA ...,piemonte
7,https://www.subito.it/auto/fiat-idea-torino-60...,Fiat Idea,2950,201104.0,257000,1,Manuale,- (Emissioni),Berlina,VENGA A TROVARCI: LA VETTURA E' DISPONIBILE DA...,piemonte
...,...,...,...,...,...,...,...,...,...,...,...
154329,https://www.subito.it/auto/seat-arona-1-0-ecot...,Seat Arona 1.0 EcoTSI XPERIENCE,16700,202112.0,33000,2,Manuale,Euro 6,SUV/Fuoristrada,"SEAT VIRTUAL COCKPIT DA 10,25 pollici\nFari Fu...",calabria
154330,https://www.subito.it/auto/peugeut-2008-cosenz...,Peugeut 2008,15999,201901.0,20000,1,Automatico,Euro 6,Monovolume,"Vendo causa inutizzo splendida peugeut 2008, c...",calabria
154331,https://www.subito.it/auto/bmw-x4-xdrive20d-xl...,BMW X4 xDrive20d xLine,25900,201802.0,110543,1,Automatico,Euro 6,SUV/Fuoristrada,DEK:[9487127]\nGRUPPO FORMULA 3 // Messina - R...,calabria
154332,https://www.subito.it/auto/audi-a-5-sportback-...,Audi a 5 sportback quattro tfsi,23700,201306.0,72000,2,Automatico,Euro 5,Station Wagon,Vendo bellissima audi a 5 tfsi con 72 mila km ...,calabria
154333,https://www.subito.it/auto/fiat-doblo-doblo-1-...,Fiat Doblo Doblò 1.6 MJT 90CV S&S PC-TN Cargo ...,11990,202104.0,143011,1,Manuale,Euro 6,Monovolume,Fiat Doblo' 1.6 MJT 90CV CARGO BUSINESS 3 POST...,calabria